apiVersion: networking.gloo.solo.io/v2
kind: VirtualDestination
metadata:
  name: foo-ha
  namespace: mesh-test
spec:
  hosts:
    - 'foo-ha.mesh-test.svc.test-ci-rs'
    - 'foo-ha.mesh-test.svc.sp-ci-rs'
  services:
    - namespace: mesh-test
      name: foo
  ports:
    - number: 80
      protocol: HTTP
---
apiVersion: resilience.policy.gloo.solo.io/v2
kind: FailoverPolicy
metadata:
  name: foo-ha
  namespace: mesh-test
spec:
  applyToDestinations:
    - kind: VIRTUAL_DESTINATION
      selector:
        name: foo-ha
  config:
    localityMappings: []
---
apiVersion: resilience.policy.gloo.solo.io/v2
kind: OutlierDetectionPolicy
metadata:
  name: foo-ha
  namespace: mesh-test
spec:
  applyToDestinations:
    - kind: VIRTUAL_DESTINATION
      selector:
        name: foo-ha
  config:
    consecutiveErrors: 2
    interval: 5s
    baseEjectionTime: 30s
    maxEjectionPercent: 100