apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: infra
  name: static-client
---
apiVersion: v1
kind: Service
metadata:
  name: static-client
  namespace: infra
spec:
  selector:
    app: static-client
  ports:
    - targetPort: 4321
      port: 4321
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: static-client
  name: static-client
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static-client
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: "true"
        app: static-client
        version: v1
    spec:
      serviceAccountName: static-client
      containers:
        - name: static-client
          image: curlimages/curl:7.84.0
          ports:
            - containerPort: 4321
              name: http
          command: ['/bin/sh', '-c', '--']
          args: ['while true; do sleep 30; done;']